---
- name: Create a new database
  become: true
  become_user: postgres
  postgresql_db:
    name: '{{ item.name }}'
    port: '{{ item.port }}'
  with_items: '{{ postgresql_databases | default({}) }}'
  when:
    - postgresql_databases is defined
